require("plugin-setup.vscode")
require("plugin-setup.lualine")
require("plugin-setup.nvim-tree")
require("plugin-setup.lsp-installer")
require("plugin-setup.lspconfig")
require("plugin-setup.cmp")
require("plugin-setup.treesitter")
require("plugin-setup.telescope")
require("plugin-setup.mini")

