#! /bin/sh

# general

xrandr -s "5120x1440_69.97"
setxkbmap de
#xrdb ~/.Xresources
export SXHKD_SHELL=/bin/dash
sxhkd &
picom &
polybar top &
feh --no-fehbg --bg-fill Downloads/wallpaper/dock.jpg &
xset r rate 150 30 &
xsetroot -cursor_name left_ptr &
xset s off &
xset -dpms &
xset +fp /home/jay/.local/share/fonts &
xset fp rehash &
xinput set-prop "ROCCAT ROCCAT Kone Aimo Mouse" "libinput Scroll Method Enabled" 0, 0, 1 &
xinput set-prop "ROCCAT ROCCAT Kone Aimo Mouse" "libinput Button Scrolling Button" 2 &

# bspwm

bspc wm -a MAIN 2560x1440+1280+0
bspc wm -a LEFT 1280x1440+0+0
bspc wm -a RIGHT 1280x1440+3840+0

bspc monitor MAIN -d   1 2 3 4 5
bspc monitor LEFT -d 1 2
bspc monitor RIGHT -d 1 2

bspc config -m MAIN left_padding -25
bspc config -m MAIN right_padding -25
bspc config -m LEFT top_padding 60

bspc monitor HDMI-A-1 -r
bspc monitor MAIN -f
bspc desktop Browse -f

bspc config border_width 	 	7
bspc config window_gap           	25

bspc config normal_border_color	 	\#333333
bspc config active_border_color  	\#333333
bspc config focused_border_color 	\#DBDBFF

bspc config split_ratio          	0.5
bspc config single_monocle	 	true

bspc config pointer_motion_interval	50

bspc pointer_modifier		 	mod4
bspc pointer_action1		 	move
bspc pointer_action3		 	resize_corner
bspc pointer_follows_focus 	 	true
bspc pointer_follows_monitor 	 	true


#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
